GET http://localhost:5172/api/questions/

###
POST http://localhost:5172/api/questions
Content-Type: application/json

{
    "lesson_id": 72,
    "stem": "bcmn hjsdgtr jdsh  hfkdshf hfks",
    "answer": "aaa",
    "alt1": "bbb",
    "alt2": "ccc",
    "alt3": "ddd",
    "alt4": "eee"
}

###
PUT http://localhost:5172/api/questions/2
Content-Type: application/json

{
    "stem": "123456" 
}

###
DELETE http://localhost:5172/api/questions/10

###

GET http://localhost:5172/uploads